#----------------------------网页信息----------------------------------
# site name
prefixName: 
siteName: 
# favicon and site master avatar
favicon: /images/favicon3.ico
avatar: /img/custom/avatar.jpg
url: https://www.zero-jan.xyz/
description: 算是半个有趣的人

# 左侧网站名称
logo:
  sakuraso: ZERO
  no: の
  shironeko: Blog

siteBuildingTime: 2021-01-00 00:00:00 # your site build time or founded date(2020-05-20 17:20:00)

#ICP备案信息尾部显示
# icp:
#   enable: true #选择性设置
#   url: http://www.beian.miit.gov.cn/state/outPortal/loginPortal.action # 备案链接
#   text: 渝ICP备19001829号 # 备案信息

cdn: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog
# cdn: https://cdn.jsdelivr.net/gh/cungudafa/cdn
pjax: 0 # 无刷新类似ajax,加速
mathjax: 1 # 1开启,公式解析

#-----------------------------导航栏--------------------------------
# 菜单导航栏
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    # 统计: {path: /analytics/ , fa: fa-line-chart },
    标签: {path: /tags, fa: fa-tags }, 
    技术: {path: /categories/技术/, fa: fa-code }, 
    # 生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-skyatlas },
    #随想: {path: /categories/随想/, fa: fa-commenting-o },
    #转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    # 悦读: {path: /books/, fa: fa-book },
    # 图集: {path: /photos/, fa: fa-photo },
    歌单: {path: /music/, fa: fa-headphones },
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    # 说说: {path: /artitalk/, fa: fa-commenting-o fa-commenting }, 
    # 追剧: {path: /movies/, fa: fa-film faa-vertical }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakuraplus/, fa: iconfont icon-sakura },
    # Lab: {path: /lab/, fa: fa-cogs },
    # valine: {path: /valine/, fa: fa-cogs }
  } }
  DIY: { path: /DIY/404, fa: fa-android faa-vertical }
  # 项目: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

#social  url, img PC端配置
social:
  gitee: {url: https://gitee.com/WXWSAND, img: /img/social/gitee.png}
  github: {url: http://github.com/FengYJ120, img: /img/social/github1.png}
  csdn: {url: https://blog.csdn.net/qq_43636199, img: /img/social/csdn.png}
  # zhihu: {url: https://www.zhihu.com/people/cungudafa, img: /img/social/zhihu.png}
  # jianshu: {url: /https://www.jianshu.com/u/9b726a534140, img: /img/social/jianshu.png}
  # sina: {url: http://weibo.com/3829198906/info, img: /img/social/sina.png}
  bilibili: {url: https://space.bilibili.com/343113645, img: /img/logo/bilibili.ico}
  # wangyiyun: {url: https://music.163.com/#/user/home?id=337394988, img: /img/social/wangyiyun.png}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2037017854&site=qq&menu=yes, img: /img/social/qq.jpeg}
  wechat: {url: /#, qrcode: /img/custom/wechat.png, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/FengYJ120, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/3829198906/info, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2037017854&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}
  csdn: {url: https://blog.csdn.net/qq_43636199, fa: fa-star, color: ff9900}

#--------------------------------首页----------------------------------------
# 首页轮播图蒙版
bgclass: t # 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
# 轮播图、如果文章没有设置photos会在这里随机取图
bg:
  # - https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/cover/13.png
  # - https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/cover/15.png
  # - https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/cover/22.png
  - https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/cover/5.png
  # - https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/cover/12.png
  # - https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/cover/2.png
  # - https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/cover/20.png

# 侧边栏
left_side_bar:
  enable: true

bg_music: https://cdn.jsdelivr.net/gh/cungudafa/cdn@latest/music/lovingstrangers.mp3

# 首页提示语
notice: 网页正在开发...
# 首页提示音
myvoice: https://cdn.jsdelivr.net/gh/cungudafa/cdn@latest/music/lovingstrangers.mp3
# 缓加载动画
lazyloadImg: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/loader/orange.progress-bar-stripe-loader.svg

# startdash url, title, desc img
startdash: 
  - {url: https://gitee.com/cungudafa/hexo-theme-sakuraplus, title: SakuraPlus, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/343113645, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: https://blog.csdn.net/qq_43636199, title: csdn, desc: 技术栈, img: /img/startdash/csdn.jpg}

# 首页文章排序规则
# Home page sort type: -1: newer first，1: older first.首页文章排序规则
homePageSortType: -1
# Home page article shown number)首页最多显示文章数
homeArticleShown: 10

# 首页卡片显示文章描述
post_description:
  enable: true # 自动获取文章前50字  

#--------------------------------功能页面-------------------------------------------
donate:
  title: 谢谢饲主了喵~
  message: 我能想到最浪漫的事，就是我喝奶茶你付钱~
  paypal: #https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPay.jpg #大图
  alipayQR: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChatPay.png #大图
  wechatQR: /img/custom/donate/WeChanQR.png
  wechatSQ: /img/custom/donate/WeChanSQ.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  enable: false
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer:  ##媒体播放引擎，移动端会禁止自动播放
  enable: true
  id: 2463172236
  server: netease
  type: playlist
  fixed: true ##开启吸底模式，固定到底部
  autoplay: false ##音频自动播放
  loop: all  ##音频循环播放, 可选值: 'all', 'one', 'none'
  order: random ##音频循环顺序, 可选值: 'list', 'random'
  preload: auto ##预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 ##默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  mutex: true ##互斥，阻止多个播放器同时播放

# Valine ##极简留言功能
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
valine:
  enable: false ##打开valine评论功能true
  appId: omjlTiRtGdasjj5OYuOotsbm-gzGzoHsz
  # U5VwYYeYlmI7C8UuoWxHrDBz-MdYXbMMI
  appKey: NOSCjRMbTj5RJC6fRybfdgap
  # SFxC9o4DBWIBfhIBOTHlaXGf
  notify: false #true自带评论mail回复提醒，第三方邮件提醒就设置为false
  verify: true #验证码
  visitor: false #统计阅读量
  comment_count: true #统计评论数
  avatar: monsterid # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: 之前评论被恶意刷了，现在重新开一个评论，大家文明留言哈~ # Comment Box placeholder
  requiredFields: ['nick','mail'] #设置必填项
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #输入框提示动画

# 动态说说页面
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://artitalk.js.org
artitalk:
  appID: DRWdKkDnsQtKxmhRhHeFUN2q-gzGzoHsz
  # Q2Ic8AOt42Hq6BDUijHQGiCa-MdYXbMMI
  appKEY: UyDddunDuBTSlwhPE2VLBQIV
  # jPCMGhA9sSJ9jO3bUB7IhpvH
  pageSize: 5 #每页显示说说的数量
  username: ZERO # Leancloud中设置的用户名
  placeholder1: 写点啥呢 # 输入框提示语
  placeholder2: 要更新头像吗？ # 头像提示语
  severurl:  #国内版填写
  lang: zh #语言English(en)及西班牙语Español(es)
  motion: 0 # 加载动画1:加载,0取消加载
  img: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/custom/avatar.jpg #用户默认头像
  bgimg: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich16.gif # 输入框小动画
  # 极简黑白主题minimalist、渐变主题gradient、壁纸wallpaper 
  # 参考 https://blog.csdn.net/cungudafa/article/details/106224223
  style: 
    enable: true #个性定制
    wallpaper: https://ae01.alicdn.com/kf/H21b5f6b8496141a1979a33666e1074d9x.jpg #https://bing.rthe.net/wallpaper  # 壁纸
    color: white   #字体颜色
    linear_gradient: rgba(255, 165, 150, 0.5) 5%, rgba(0, 228, 255, 0.35) 95% # 渐变规律颜色+百分比 rgb(109, 208, 242) 15%, rgb(245, 154, 190) 85%
    border_right_color: '#FFC0BE' #三角颜色
    animation: false #true打开动画渐变渲染(壁纸和动画渐变渲染建议只开一个)

# 评论 
gitalk:
  enable: true
  # 是否自动展开评论框
  autoExpand: true
  clientID: d933d6160f7fb7b973f5
    # 0ef89257a5aaf8e30d52 #GitHub Application Client ID
  clientSecret: 0db2ba7d019ab697eeb5f704ccef83ccec059c0c
    # 046080d6bfacf6607a3c48c349d945069f28ae72 #GitHub Application Client Secret
  repo: FengYJ120.github.io  #博客的仓库名称(注意不是地址)
  owner: FengYJ120 #github用户名
  admin: FengYJ120 #github用户名
  labels: 'gitalk' #github issue 对应的issue标签（新建一个）
  distractionFreeMode: true #无干扰模式，不需要更改


# 友链页信息,tips支持html语言
mylinkinfo:
  enable: true
  tips: ' <p style="font-size: 13px;color: #ff9999;"> 
            1. 为保证友链质量，新申请的友链将经过筛选，请在收到我的回复邮件后再于贵站添加本站链接。<br>
            2. 原则上已添加的友链不会轻易删除，如遇死链、改变网站用途，将单独移至“阵亡将士”分类中，下次清理时未整改的将移除；<br>
            3. 如遇盗版、破解、网页植入挖矿脚本、极低质量内容、单方面移除本站链接，将直接移除，恕不另行通知。
          </p>'
  name: ZERO-JAN
  desc: 算是半个有趣的人
  url: https://www.zero-jan.xyz
  img: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/img/custom/avatar.jpg

# botui https://www.bootcdn.cn/botui/
# 简介在about页面需要单独配置（/js/third-party/botui.js）

# books、movies页面使用的是豆瓣插件，在主题目录配置

# Whether to display post-calender in the `archive` page
# 设置在归档页面achive中是否显示'文章日历'控件
postCalendar: true 

# 仿volantis主题小标签美化 
# 更多详细使用参考 https://volantis.js.org/v2/tag-plugins/
v_tags:
  enable: true

#--------------------------------其他功能--------------------------------------------
# 简易信息聚合,站点共享
rss: /atom.xml

# Whether to activate the copyright information of the blog and author when copying the post content.
# minCharNumber: Approve copyright information by copying at least how many characters.
# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: false # 代码块是否可复制,true允许,false加上文章信息
  minCharNumber: 64 # 至少复制多少个字符就追加版权信息.
  description: 版权声明：本文为博主原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接和本声明。

# 查看大图
fancybox:
  enable: true

# 外链转知乎卡片形式 
linkcard:
  enable: true #貌似和valine刷新有点冲突 ，排查中

# 是否开启字数统计 (可以在post设置no_word_count: true)
#不需要使用，直接设置值为false，或注释掉
word_count: true

# busuanzi(http://busuanzi.ibruce.info/) website statistics
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次

# Add google analytics configuration
# 添加 Google Analytics 配置
googleAnalytics:
  enable: true
  id: G-8SP07H50X6

# Add baidu analytics configuration
# 添加 baidu Analytics 配置 https://tongji.baidu.com/
baiduAnalytics:
  enable: true # 百度分析
  id: e39c3b3f464575d5a7704f786347e0bc

# 开启百度站长平台自动推送(https://ziyuan.baidu.com/linksubmit/index)
# 页面被访问了，就会被推送过去。
baidu_push: true

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
  
# widgetpack 星星评分
# To get your ID visit https://widgetpack.com
widgetpack:
  enable: true #false
  id: 29019
    # 23889 #<app_id>
  color: fc6423

# Online contact ##在线聊天 https://www.daocloud.io/
daovoice: 
  enable: true
  app_id: 90895c08 ##这里替换成你DaoVoice上的appid

# 天气显示 https://dev.qweather.com/
weather:
  enable: false
  app_id: ee3a952a102b4365ab55dcc08ab271a0

# 建议一项只开一个
js:
  hititle: true # 浏览器搞笑标题
  KeyBlock: true # 按键屏蔽,不能F12调试和查看源代码
  bg:
    sakura_petals: false  # 仅在首页花瓣飘落（大内存）
    snow_petals: false # 雪花飘落（大内存）
    piao: false # 飘动彩带
    canvas_nest: false # 粒子飘浮
    live2d_widget: false # 看板娘 需jq（大内存）
    bgchange: false # 是否开启壁纸切换
  clink:
    word: true # 点击出现字效
    love: false # 点击出现爱心
    cursor: false # 星星跟随坠落(大内存)

#------------------------------CDN，非必要，不要修改-----------------------------

libs:
  css:
    googlefonts: https://fonts.googleapis.com/css?family=Noto+SerifMerriweather|Merriweather+Sans|Source+Code+Pro|Ubuntu:400,700|Noto+Serif+SC
    style: /css/style.css #https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/style.css # 
    lib: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/css/lib.min.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/lib.min.css
    font: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/css/font.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/font.css
    insight: /css/insight.css
    tags: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/css/tags.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/tags.css
    fancybox: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/css/jquery.fancybox.min.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/jquery.fancybox.min.css
    sharejs: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/css/sharejs.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/sharejs.css
    tocbot: https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.css
    live2d_widget: https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css
    logo:
      enable: true # 自定义logo
      logo: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/css/logo.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/logo.css
      logo_fonts: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/fonts/LOGO/logo.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/fonts/LOGO/logo.css
  js:
    jquery: https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
    linkcard: /js/linkcard.js
    lib: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/js/lib.min.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/lib.min.js
    clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
    InsightSearch: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/js/InsightSearch.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/InsightSearch.js
    sakura_app: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/js/sakura-app.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/sakura-app.js  #/js/sakura-app.js
    busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js 
    fancybox: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/js/jquery.fancybox.min.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/jquery.fancybox.min.js
    echarts: https://cdn.jsdelivr.net/gh/FengYJ120/CDN/MyBlog/js/echarts.min.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/echarts.min.js
    valine: https://unpkg.com/valine/dist/Valine.min.js
    sakura_petal: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/sakura.js #other
    hititle: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/hititle.js 
    KeyBlock: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/noSomeKey.js #按键屏蔽,不能F12调试和查看源代码
    sakura_petals: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/sakura.js  #仅在首页花瓣飘落（大内存）
    snow_petals: https://cdn.jsdelivr.net/gh/Yafine/cdn@2.5/source/js/snow1.js
    piao: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/piao.js #飘动彩带
    live2d_widget: https://cdn.jsdelivr.net/gh/cungudafa/cdn/live2d-widget/autoload.js
    word: https://cdn.jsdelivr.net/gh/wallleap/cdn/js/shehuizhuyi.js #点击出现字效
    love: https://cdn.jsdelivr.net/gh/wallleap/cdn/js/love.js #点击出现爱心
    cursor: https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.1.2/js/cursor.js # 星星跟随坠落(大内存)
    canvas_nest: https://cdn.jsdelivr.net/gh/wallleap/cdn/js/canvas-nest.min.js # 粒子飘浮


